application: tf2find
version: 2-0
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /searchdescription\.xml
  static_files: searchdescription.xml
  upload: searchdescription\.xml

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /scripts
  static_dir: scripts

- url: /(.*\.(png))
  static_files: static/\1
  upload: static/(.*\.(png))

- url: /cache/.*
  script: main.cache
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"

- name: jinja2
  version: "latest"

- name: markupsafe
  version: "latest"
